import '@/core/styles/globals.scss';
import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
const inter = Rubik({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} app dark`}>{children}</body>
    </html>
  );
}
